#!/bin/bash
# SPDX-License-Identifier: MIT
# Copyright (c) 2022,2023 Gene C
#
# installer script for dns_tools
# e.g. Call from PKGBUILD:  
#   ./do-install ${pkgdir}
# gene c (2022)
#
dest="$1"
self="dns_tools"

info="README.md CHANGELOG.md packaging"
infodir="/usr/share/${self}"

etc="cron scripts conf.d"
etcdir="/etc/dns_tools"

license="LICENSE"
licensedir="/usr/share/licenses/${self}"

# list apps without the ".py" or leave empty string
apps=('dns-tool dns-prod-push dns-serial-bump')

# so can make app link in /usr/bin
sitedir=$(/usr/bin/python3 -c "import site; print(site.getsitepackages()[0])")

if [ ! -d "$dest" ] ; then
    echo 'Missing destination directory'
    exit 1
else
    /usr/bin/rsync --mkpath -a ${etc} ${dest}${etcdir}
    /usr/bin/rsync --mkpath -a ${info} ${dest}${infodir}
    /usr/bin/rsync --mkpath -a ${license} ${dest}/${licensedir}/${license}

    #
    # Ensure no pip config is used.
    #
    export PIP_CONFIG_FILE=/dev/null
    pipopts="--isolated --ignore-installed --no-deps"
    /usr/bin/pip install --root="${dest}" $pipopts dist/*.whl

    # link(s) in /usr/bin/
    if [ -v apps ] ; then
        /usr/bin/mkdir -p "${dest}/usr/bin"
        for app in ${apps[@]}
        do
            /usr/bin/ln -sf ${sitedir}/${self}/${app}.py ${dest}/usr/bin/${app}
        done
    fi
    exit 0
fi
