py.install_sources(
     '_config_checks.py',
     '_config.py',
     '_config_read.py',
     '_config_utils.py',
     '_dnsserv.py',
     '__init__.py',
     '_keyopts.py',
     '_normalize_paths.py',
     '_parse_args.py',
     '_prodopts_avail.py',
     '_prodopts_base.py',
     'prodopts.py',
     '_toolopts_avail.py',
     '_toolopts_base.py',
     'toolopts.py',
  subdir: 'dns_tools/config'
)
