#!/usr/bin/bash
#
# Source code checks.
#
# Run in src dir
# i.e. cd src
# Requires
# - pylint
# - pycodestyle
# - mypy

mod_dir="src/dns_tools"
echo 'Check module'
PYTHONPATH=./src pylint $mod_dir/*y $mod_dir/*/*py
PYTHONPATH=./src pycodestyle --max-line-length=110 $mod_dir/*y $mod_dir/*/*py

mypy --check-untyped-defs --follow-untyped-imports $mod_dir

echo ''
echo 'Check tests'
mypy --check-untyped-defs --follow-untyped-imports tests/


