#!/bin/bash
# SPDX-License-Identifier: MIT
# Copyright (c) 2022,2023 Gene C
#
# installer script for dns_tools
# e.g. Call from PKGBUILD:  
#   ./do-install ${pkgdir}
# gene c (2022)
#
dest="$1"
self="dns_tools"

info="README.rst Docs packaging"
infodir="/usr/share/${self}"

etc="cron scripts conf.d"
etcdir="/etc/dns_tools"

license="Docs/License/License.rst"
licensedir="/usr/share/licenses/${self}"

# list apps without the ".py" or leave empty string
apps=('dns-tool dns-prod-push dns-serial-bump')

# so can make app link in /usr/bin
sitedir=$(/usr/bin/python3 -c "import site; print(site.getsitepackages()[0])")
installdir="${dest}${sitedir}"
app_location="${sitedir}/dns_tools/apps"

uv_opts=(
    --python /usr/bin/python
    --system
    --no-build-isolation
    --link-mode=copy
    --compile-bytecode
)

if [ ! -d "$dest" ] ; then
    echo 'Missing destination directory'
    exit 1
else
    /usr/bin/rsync --mkpath -a ${etc} ${dest}${etcdir}
    /usr/bin/rsync --mkpath -a ${info} ${dest}${infodir}
    /usr/bin/rsync --mkpath -a ${license} ${dest}/${licensedir}/

    /usr/bin/uv pip install ${uv_opts[@]} --target "$installdir" dist/*.whl
    /usr/bin/rm -rf "$installdir"/.lock

    # link(s) in /usr/bin/
    if [ -v apps ] ; then
        /usr/bin/mkdir -p "${dest}/usr/bin"
        for app in ${apps[@]}
        do
            /usr/bin/ln -sf ${app_location}/${app}.py ${dest}/usr/bin/${app}
        done
    fi
    exit 0
fi
