#!/bin/bash
#
# Install
# - arguments:
#   - no args: destination is "build/pkg".
#   - destination   =>  install to this directory
#

if (( $# < 1 )) ; then
    dest='build/pkg'
else
    dest="$1"
fi

dest=$(realpath "$dest")

/usr/bin/meson install -C build/release --destdir "$dest" > /dev/null

exit 0
